spring:
  application:
    name: view_files
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
  resources:
    static-locations: classpath:/static/
server:
  port: 9100
weiyan:
  port: 9100
jwt:
  config:
    key: misterwei
